sudo: false

language: python

dist: trusty

os:
    - linux

before_install:
    - export DISPLAY=:99.0
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi

install:
    - curl -L https://github.com/GafferHQ/gaffer/releases/download/0.53.6.0/gaffer-0.53.6.0-linux.tar.gz > $GAFFER_DOWNLOAD_NAME
    - mkdir -p $GAFFER_EXTRACT_DIRECTORY
    - tar xzf $GAFFER_DOWNLOAD_NAME -C $GAFFER_EXTRACT_DIRECTORY --strip-components=1
    - curl -L $PIP_URL > $PIP_OUTPUT
    - $GAFFER_ROOT/bin/python $PIP_OUTPUT
    - $GAFFER_ROOT/bin/python -m pip install --target=$GAFFER_ROOT/python mock
    - $GAFFER_ROOT/bin/python -m unittest discover -p "*Test.py"

script:
    - cd $TRAVIS_BUILD_DIR/python
    - $GAFFER_ROOT/bin/gaffer test GafferDeadlineTest
    - $GAFFER_ROOT/bin/gaffer test GafferDeadlineUITest

matrix:
    include:
        - python: "2.7"
env:
    global:
        - GAFFER_DOWNLOAD_NAME=$HOME/gaffer_download.tar.gz
        - GAFFER_EXTRACT_DIRECTORY=$HOME/gaffer_download
        - PIP_URL=https://bootstrap.pypa.io/get-pip.py
        - PIP_OUTPUT=$HOME/get-pip.py
        - DEADLINE_DEPENDENCY_SCRIPT_PATH=$TRAVIS_BUILD_DIR/gaffer_batch_dependency.py
        - GAFFER_ROOT=$GAFFER_EXTRACT_DIRECTORY
        - LD_LIBRARY_PATH=$GAFFER_ROOT/lib
        - PATH=$GAFFER_ROOT/bin:$PATH
        - PYTHONHOME=$GAFFER_ROOT
        - PYTHONPATH=$GAFFER_ROOT/python:$TRAVIS_BUILD_DIR/python:$PYTHONPATH
        - GAFFER_EXTENSION_PATHS=$TRAVIS_BUILD_DIR

